#
# (c) Copyright 2015-2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

# This task uses the bminfo struct from get-baremetal-info.yml to derive a
# bunch of convenience variables that are used in various other plays. It then
# goes further and figures out the name of the network interface that Cobbler
# is using, by comparing the baremetal CIDR specified in the model with the
# actual values in "ip a" on localhost.

cobbler_is_sles: True

cobbler_remove_packages:
  - atftp

cobbler_install_packages:
  - tftp
  - cobbler
  - xinetd
  - dhcp-server
  - syslinux
  - shim
  - python-jsonschema
  - fence-agents
  - python-passlib

cobbler_tftp_service_name: tftp
cobbler_dhcp_package_name: dhcp-server
cobbler_dhcp_service_name: dhcpd
cobbler_dhcp_config_file: /etc/dhcpd.conf
cobbler_bootloader_sources:
  - { src: "/usr/share/syslinux/menu.c32", filename: "menu.c32" }
  - { src: "/usr/share/syslinux/pxelinux.0", filename: "pxelinux.0" }
  - { src: "/usr/lib64/efi/shim.efi", filename: "shim.efi.signed" }
cobbler_tftp_dir: /srv/tftpboot
