#
# (c) Copyright 2017,2018 SUSE LLC
#
---

- hosts: localhost
  roles:
   - cobbler

  tasks:
    - include: roles/cobbler/tasks/set-vars.yml

    - include: roles/cobbler/tasks/create-sles-grub2.yml node={{ nodelist }}
