#
# (c) Copyright 2019 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# This task file expects 2 parameters:
#   check_distro: the name of the distro to check for (required)
#   check_delay: delay between retry attempts (optional, default=1)
# Results:
#   cobbler_distro_exists_result - registered result from cobbler command
---

- name: cobbler | check-distro-exists | Check {{ check_distro }} distro exists?
  become: yes
  command: >-
    cobbler distro report --name="{{ check_distro }}"
  register: cobbler_distro_exists_result
  failed_when: false
  changed_when: false
  retries: 5
  delay: "{{ check_delay | default(1) }}"
  until: >-
    "error(111, 'Connection refused')" not in cobbler_distro_exists_result.stderr

- name: cobbler | check-distro-exists | Report if multiple attempts required
  debug: var=cobbler_distro_exists_result
  when: cobbler_distro_exists_result.attempts > 0

