#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- name: cobbler | configure | Set vars dependent on target OS
  include_vars: "{{ ansible_os_family.split(' ')[0] | lower | replace('open','') }}.yml"

# Cobbler deb package installs conf file into wrong folder /etc/apache2/conf.d
- name: cobbler | configure | Debian - symlink cobbler apache configuration
  become: yes
  file:
    src: /etc/apache2/conf.d/cobbler.conf
    dest: /etc/apache2/conf-available/cobbler.conf
    state: link
  when: not cobbler_is_sles

- name: cobbler | configure | Debian - enable cobbler apache configuration
  become: yes
  command: a2enconf cobbler
  when: not cobbler_is_sles

- name: cobbler | configure | Suse - create apache configuration for /srv
  become: yes
  template: src=srv.conf.j2 dest=/etc/apache2/conf.d/srv.conf
  when: cobbler_is_sles

- name: cobbler | configure | Debian - create apache configuration for /srv
  become: yes
  template: src=srv.conf.j2 dest=/etc/apache2/conf-available/srv.conf
  when: not cobbler_is_sles

- name: cobbler | configure | Debian - enable apache configuration for /srv
  become: yes
  command: a2enconf srv
  when: not cobbler_is_sles

- name: cobbler | configure | set default passwd
  set_fact: cobbler_default_passwd="{{ item }}"
  with_password: /tmp/cobbler_setup  encrypt=sha512_crypt

- name: cobbler | configure | rm temp file
  file:
    path: /tmp/cobbler_setup
    state: absent
    recurse: no

- name: cobbler | configure | Adding cobbler settings file
  become: yes
  template: src=settings.j2 dest=/etc/cobbler/settings

- name: cobbler | configure | Suse - fix cobbler tftpd template
  become: yes
  lineinfile:
    dest: /etc/cobbler/tftpd.template
    state: present
    regexp: '^\s*server_args\s*=.*'
    line: '        server_args             = -u tftp -B 1380 -vvvv -s $args'
  when: cobbler_is_sles

- name: cobbler | configure | Create directory for preseed content
  become: yes
  file:
    path: /srv/www/preseed
    state: directory
    mode: 0755

- name: cobbler | configure | Copy preseed content
  become: yes
  copy: src={{ item }} dest=/srv/www/preseed
  with_items:
     - partition-pxe
     - partition-uefi
     - configure_partitioning
     - configure_kdump
     - bnx2x.conf
     - update_fcoe_udev.py

- name: cobbler | configure | Add option to add gateway
  become: yes
  template:
      src: configure_network.sh.j2
      dest: /srv/www/preseed/configure_network.sh

- name: cobbler | configure | set timestamp for installs
  become: yes
  shell: date +%Y%m%d%H%M%S > {{ local_timestamp_file }}

# Temp until CI updated
- name: cobbler | configure | Set local stamp
  become: yes
  copy: src={{ local_timestamp_file }} dest=/etc/cobbler_ardana_installed

# Get syslinux bootloaders
- name: cobbler | configure | Create bootloader directory
  become: yes
  file:
    path: /var/lib/cobbler/loaders
    state: directory
    mode: 0755

# Copy module behaves weird with with_items
- name: cobbler | configure | Copy various loaders to cobbler loaders dir
  become: yes
  shell: cp -Lf {{ item.src }} /var/lib/cobbler/loaders/{{ item.filename }}
  with_items: cobbler_bootloader_sources

- name: cobbler | configure | Adding cobbler dhcp template
  become: yes
  template: src=cobbler.dhcp.template.j2 dest=/etc/cobbler/dhcp.template

- name: cobbler | configure | Enable apache modules
  become: yes
  command: "a2enmod {{ item }}"
  with_items:
    - proxy
    - proxy_http
    - access_compat

- name: cobbler | configure | Check SLES distro exists?
  include: check-distro-exists.yml
  vars:
    check_distro: "{{ sles_version_name }}-x86_64"
    check_delay: 5

- name: cobbler | configure | Locate distro_signatures.json files
  set_fact:
     distro_signatures_files:
       - /etc/cobbler/distro_signatures.json
       - /var/lib/cobbler/distro_signatures.json
  when: cobbler_distro_exists_result.rc != 0

- name: cobbler | configure | Fix line endings in distro_signatures.json files
  become: yes
  replace: dest="{{ item }}" regexp="\\r"
  with_items: distro_signatures_files
  when: cobbler_distro_exists_result.rc != 0
