#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Playbook for installing cobbler
---
- name: cobbler | install | Set vars dependent on target OS
  include_vars: "{{ ansible_os_family.split(' ')[0] | lower | replace('open','') }}.yml"

# Remove any old atftp (this also stops the service)
- name: cobbler | install | Remove conflicting packages
  become: yes
  package:
    name: "{{ item }}"
    state: absent
  with_items: cobbler_remove_packages

- name: cobbler | install | Install cobbler and dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: cobbler_install_packages

- name: cobbler | install | Create validate json script
  copy:
    src: validate_yaml
    dest: ~/
    mode: "u=rwx"

- name: cobbler | install | Validate json schema
  command: ~/validate_yaml {{ baremetal_config_schema }} {{ baremetal_config }}

- name: cobbler | install | stop tftpd
  become: yes
  command: "systemctl stop {{ cobbler_tftp_service_name }}"

- name: cobbler | install | disable tftpd
  become: yes
  command: "systemctl disable {{ cobbler_tftp_service_name }}"

- name: cobbler install | Get interface name
  shell: netstat -ie | grep -B1 "{{ cobbler_server_ip_addr }}" | head -n1 | awk '{ print $1 }'
  register: interface_name
  changed_when: false

- name: check if interface matches baremetal file
  fail:
    msg: "Please update your baremetal file with the new interface name {{ interface_name.stdout }}"
  when: interface_name.stdout != cobbler_server_interface

# isc-dhcp-server will fail to install if dest=/etc/default/isc-dhcp-server is not present
# and containing the INTERFACES param
# TODO - Log bugzilla for this packaging issue
- name: cobbler | install | Create isc-dhcp-server conf file
  become: yes
  template:
    src: isc-dhcp-server.j2
    dest: /etc/default/isc-dhcp-server
  when: not cobbler_is_sles

- name: cobbler | install | Install isc-dhcp-server
  become: yes
  package:
    name: "{{ cobbler_dhcp_package_name }}"
    state: present

- name: cobbler | install | Create dhcp conf file
  become: yes
  template:
    src: dhcpd.conf.j2
    dest: "{{ cobbler_dhcp_config_file }}"

- name: cobbler | install | Populate isc-dhcp-server sysconfig file
  become: yes
  lineinfile:
    dest: /etc/sysconfig/dhcpd
    regexp: '^DHCPD_INTERFACE=.*'
    line: 'DHCPD_INTERFACE="{{ cobbler_server_interface }}"'
  when: cobbler_is_sles

- name: cobbler | install | Create ipmi lanplus power file
  become: yes
  copy:
    src: fence_ipmitool.template
    dest: /etc/cobbler/power/fence_ipmitool.template

- name: cobbler | install | Get deployer pub ssh key
  command: cat {{ ardanauser_deployer_home }}/.ssh/id_rsa.pub
  register: sshkeyoutput

- name: cobbler | install | Save deployer ssh key
  set_fact:
    deployer_ssh_pub_key: "{{ sshkeyoutput.stdout }}"

- name: cobbler | install | Install kickstarts
  become: yes
  template:
    src: "{{ item[0].kickstart }}.j2"
    dest: "/var/lib/cobbler/kickstarts/{{ item[0].kickstart }}-{{ item[1].id }}"
  when:
    "'{{ item[0].name }}-{{ item[0].arch }}' == '{{ item[1].distro_id }}'"
  with_nested:
      - remote_distros
      - bminfo.servers
