#
# (c) Copyright 2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- include_vars: ../../deployer-setup/defaults/ardana_tar_locations.yml

- name: cobbler | populate-sles | Check SLES Profile
  become: yes
  command: >
    cobbler profile report --name="{{ sles_profile_name }}-x86_64"
  register: _sles12_profile_exist_result
  failed_when: false
  changed_when: false

- name: cobbler | populate-sles | Install SLES kickstart
  become: yes
  template:
    src: "sles12sp3-autoyast.xml.j2"
    dest: "/var/lib/cobbler/kickstarts/sles12sp3-autoyast.xml"
    owner: "root"
    group: "root"
    mode: 0644

- name: cobbler | populate-sles | Test for SLES ISO file in home folder
  stat:
    path: "{{ ardanauser_deployer_home }}/{{ deployer_sles12_iso }}"
    get_checksum: no
    get_md5: no
  register: _deployer_sles12_iso_exists_result

- name: cobbler | populate-sles | Test for SLES ISO mounted at /media/cdrom
  stat:
    path: "/media/cdrom/suse"
    get_checksum: no
    get_md5: no
  register: _deployer_sles12_cdrom_exists_result

- name: cobbler | populate-sles | Create temporary mount directory
  become: yes
  command: mktemp -d -p /srv
  register: _mount_tmpdir
  when: (_deployer_sles12_iso_exists_result.stat.exists or
         _deployer_sles12_cdrom_exists_result.stat.exists) and
         _sles12_profile_exist_result.rc != 0

- name: cobbler | populate-sles | Mount SLES ISO
  become: yes
  command: >
    mount -o ro,loop "{{ ardanauser_deployer_home }}/{{ deployer_sles12_iso }}" \
        "{{ _mount_tmpdir.stdout }}"
  when: _deployer_sles12_iso_exists_result.stat.exists
        and _sles12_profile_exist_result.rc != 0

- name: cobbler | populate-sles | Rsync SLES ISO to temporary folder
  become: yes
  synchronize:
    src: "/media/cdrom/"
    dest: "{{ _mount_tmpdir.stdout }}/"
    delete: true
    times: no
    rsync_opts:
      - "--exclude=ardana"
  when: _deployer_sles12_cdrom_exists_result.stat.exists
        and not _deployer_sles12_iso_exists_result.stat.exists
        and _sles12_profile_exist_result.rc != 0

- name: cobbler | populate-sles | Cobbler import
  become: yes
  command: >
    cobbler import
    --path {{ _mount_tmpdir.stdout }}
    --name {{ sles_profile_name }}
    --kickstart /var/lib/cobbler/kickstarts/sles12sp3-autoyast.xml
  when: (_deployer_sles12_iso_exists_result.stat.exists or
         _deployer_sles12_cdrom_exists_result.stat.exists) and
         _sles12_profile_exist_result.rc != 0

- name: cobbler | populate-sles | Umount ISO
  become: yes
  command: >
    umount {{ _mount_tmpdir.stdout }}
  when: _deployer_sles12_iso_exists_result.stat.exists
        and _sles12_profile_exist_result.rc != 0

- name: cobbler | populate-sles | Remove temporary directory
  become: yes
  file:
    path: "{{ _mount_tmpdir.stdout }}"
    state: absent
  when: (_deployer_sles12_iso_exists_result.stat.exists or
         _deployer_sles12_cdrom_exists_result.stat.exists) and
         _sles12_profile_exist_result.rc != 0
