#
# (c) Copyright 2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: cobbler | synchronize-iso | Check if ISO exists
  stat:
    path: "{{ iso_src }}"
    get_checksum: no
    get_md5: no
  register: _iso_exists

- name: cobbler | synchronize-iso | Create temporary mount directory
  command: mktemp -d
  register: _mount_tmpdir
  when: _iso_exists.stat.exists

- name: cobbler | synchronize-iso | Mount ISO
  become: yes
  shell: |
    mount -o loop "{{ iso_src }}" "{{ _mount_tmpdir.stdout }}"
  when: _iso_exists.stat.exists

- name: cobbler | synchronize-iso | Create ISO destination
  become: yes
  file:
    path: "{{ iso_dest }}"
    state: directory
    mode: 0755
  when: _iso_exists.stat.exists

- name: cobbler | synchronize-iso | Synchronize ISO
  become: yes
  synchronize:
    src: "{{ _mount_tmpdir.stdout }}/"
    dest: "{{ iso_dest }}"
  when: _iso_exists.stat.exists

- name: cobbler | synchronize-iso | Umount ISO
  become: yes
  shell: |
    umount {{ _mount_tmpdir.stdout }}
  when: _iso_exists.stat.exists

- name: cobbler | synchronize-iso | Remove temporary mount directory
  file:
    path: "{{ _mount_tmpdir.stdout }}"
    state: absent
  when: _iso_exists.stat.exists

